name: Sponsors
on:
  workflow_dispatch:

jobs:
  sponsors:
    name: "Sponsors"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node v18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm ci
      - name: Build SVG image
        run: npm run build
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_OPENCOLLECTIVE_KEY: ${{ secrets.SPONSORKIT_OPENCOLLECTIVE_KEY }}
      - name: Print cache
        run: cat sponsorkit/.cache.json
      - name: Configure GIT
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Commit
        run: git add *.svg && git commit -m "Update SVG"
      - name: Push
        run: git push
