name: Sponsors
on:
  workflow_dispatch:

jobs:
  sponsors:
    name: "Sponsors"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node v18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm ci
      - name: Build SVG image
        run: npm run build
